<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Task;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTasksForForUser($userId,$state = Task::TODOTASK){
        $qb = $this->createQueryBuilder('t')
            ->select('t')
            ->where('t.user = :user_id')
            ->andWhere('t.state = :state')
            ->setParameter('user_id',$userId)
            ->setParameter('state',$state);

        return $qb->getQuery()
            ->getResult();
    }
}
